---
title: carlvlew.is
timezone: America/New_York
locale: en
title_separator: "-"
name: "@carlvlewis"
baseurl: "/carlvlew.is"
url: ""
repository: codeforamerica/carlvlew.is
teaser:
words_per_minute: 50
comments:
  provider: disqus
  disqus:
    shortname: carlvlewis
    Key:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: master
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: docs/_data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path:
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:
twitter:
  username: carlvlewis
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:
analytics:
  provider: true
  google:
    tracking_id: UA-102583563-1
author:
  name: Carl V. Lewis
  avatar: http://cvlassets.s3.amazonaws.com/1697569.jpg
  bio: data visualization, civic-tech, digital humanities, media futurism.
  location: 38.627003, -90.1999
  email: hello@carlvlew.is
  uri:
  bitbucket:
  bl.ocks: http://bl.ocks.org/carlvlewis
  codepen: carlvlewis
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: carlvlewis
  google_plus: carlvlewis
  keybase: carlvlewis
  instagram: carlvlewis
  lastfm:
  linkedin: carlvlewis
  quora: https://quora.com/profile/carl-v-lewis-1
  pinterest: carlvlewis
  soundcloud:
  stackexchange: https://opendata.stackexchange.com/users/14970/carl-v-lewis
  stackoverflow:
  steam:
  tumblr:
  twitter: carlvlewis
  vine:
  weibo:
  youtube:
include:
  - ".htaccess"
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - ".asset-cache"
  - ".bundle"
  - ".jekyll-assets-cache"
  - ".sass-cache"
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - "/docs"
  - "/test"
keep_files:
  - ".git"
  - ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-admin
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
whitelist:
  - jekyll-admin
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
autopages:
  enabled: true
  categories:
    slugify:
      mode: raw
      cased: true
    layouts:
      - 'categories.html'
    title: ':cat'
    permalink: '/category/:cat'
  collections:
    slugify:
      mode: raw
      cased: true
    layouts:
      - 'collections.html'
    title: ':coll'
    permalink: '/:coll'
  tags:
    slugify:
      mode: raw
      cased: true
    layouts:
      - 'tags.html'
    title: ':tag'
    permalink: '/tag/:tag'

category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
tag_archive_portfolio:
  type: liquid
  path: "/portfolio-tags/"
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: '_posts'
    values:
      permalink: /:title/
      layout: single
      author: Carl V. Lewis
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: '_portfolio'
    values:
      layout: single
      permalink: /portfolio/:title/
      author_profile: true
